const fs = require("fs");
const path = require("path");

const [, , targetPathArg, base64PathArg] = process.argv;

if (!targetPathArg || !base64PathArg) {
  console.error(
    "Usage: node restore_buyer_orders_from_b64.js <targetPath> <base64Path>"
  );
  process.exit(1);
}

const targetPath = path.resolve(process.cwd(), targetPathArg);
const base64Path = path.resolve(process.cwd(), base64PathArg);

const tsxLines = [
  'import React, { useEffect, useMemo, useState } from "react";',
  'import { useNavigate } from "react-router-dom";',
  "",
  "type OrderLike = {",
  "  id: string;",
  "  status?: string | null;",
  "  paymentStatus?: string | null;",
  "  createdAt?: string | null;",
  "  totalCents?: number | null;",
  "  total?: number | null;",
  "};",
  "",
  'type FilterKey = "all" | "unpaid" | "paid" | "fulfilled" | "cancelled" | "refunded";',
  "",
  "const FILTER_OPTIONS: Array<{ label: string; value: FilterKey }> = [",
  '  { label: "All", value: "all" },',
  '  { label: "Unpaid", value: "unpaid" },',
  '  { label: "Paid", value: "paid" },',
  '  { label: "Fulfilled", value: "fulfilled" },',
  '  { label: "Cancelled", value: "cancelled" },',
  '  { label: "Refunded", value: "refunded" },',
  "];",
  "",
  "function normalizeStatus(status?: string | null) {",
  '  return (status ?? "").toString().trim().toUpperCase();',
  "}",
  "",
  "function isUnpaidStatus(status: string) {",
  "  return /UNPAID|PLACED|PENDING|PENDING_PAYMENT/.test(status);",
  "}",
  "",
  "function formatMoney(order: OrderLike) {",
  "  const cents =",
  "    (typeof order.totalCents === \"number\" && order.totalCents) ||",
  "    (typeof order.total === \"number\" ? order.total * 100 : null);",
  "  if (cents != null) {",
  "    return `$${(cents / 100).toFixed(2)}`;",
  "  }",
  "  return \"—\";",
  "}",
  "",
  "async function fetchOrdersFallback(): Promise<OrderLike[]> {",
  "  const token =",
  '    localStorage.getItem("token") || localStorage.getItem("authToken") || "";',
  "  const res = await fetch(\"/api/buyer/orders\", {",
  "    headers: token ? { Authorization: `Bearer ${token}` } : undefined,",
  "  });",
  "  if (!res.ok) {",
  "    const text = await res.text().catch(() => \"\");",
  "    throw new Error(`Failed to load orders (${res.status}): ${text}`);",
  "  }",
  "  const data = await res.json();",
  "  if (Array.isArray(data)) return data;",
  "  if (Array.isArray(data?.items)) return data.items;",
  "  if (Array.isArray(data?.orders)) return data.orders;",
  "  return [];",
  "}",
  "",
  "export default function BuyerOrdersPage() {",
  "  const navigate = useNavigate();",
  "  const [orders, setOrders] = useState<OrderLike[]>([]);",
  "  const [filter, setFilter] = useState<FilterKey>(\"all\");",
  "  const [loading, setLoading] = useState(true);",
  "  const [error, setError] = useState<string | null>(null);",
  "",
  "  useEffect(() => {",
  "    let mounted = true;",
  "    const fetchOrders = async () => {",
  "      setLoading(true);",
  "      setError(null);",
  "      try {",
  "        let list = null;",
  "        try {",
  "          const shared = await import(\"../../shared/api/http\");",
  "          if (shared && typeof shared.fetchJson === \"function\") {",
  "            const data = await shared.fetchJson(\"/api/buyer/orders\");",
  "            if (Array.isArray(data)) list = data;",
  "            else if (Array.isArray(data?.items)) list = data.items;",
  "            else if (Array.isArray(data?.orders)) list = data.orders;",
  "          }",
  "        } catch (ignored) {",
  "          // ignore",
  "        }",
  "        const finalList = (list ?? (await fetchOrdersFallback())) as OrderLike[];",
  "        if (mounted) setOrders(finalList);",
  "      } catch (err) {",
  "        if (mounted) setError(err?.message ?? \"Failed to load orders\");",
  "      } finally {",
  "        if (mounted) setLoading(false);",
  "      }",
  "    };",
  "    fetchOrders();",
  "    return () => {",
  "      mounted = false;",
  "    };",
  "  }, []);",
  "",
  "  const filteredOrders = useMemo(() => {",
  "    return orders.filter((order) => {",
  "      const status = normalizeStatus(order.status || order.paymentStatus);",
  "      if (filter === \"all\") return true;",
  "      if (filter === \"unpaid\") return isUnpaidStatus(status);",
  "      if (filter === \"paid\") return status.includes(\"PAID\");",
  "      if (filter === \"fulfilled\") return status.includes(\"FULFILLED\");",
  "      if (filter === \"cancelled\") return status.includes(\"CANCELLED\");",
  "      if (filter === \"refunded\") return status.includes(\"REFUNDED\");",
  "      return true;",
  "    });",
  "  }, [orders, filter]);",
  "",
  "  return (",
  '    <div style={{ padding: 16 }}>',
  '      <h1 style={{ fontSize: 20, fontWeight: 700, marginBottom: 12 }}>My Orders</h1>',
  '      <div style={{ display: \"flex\", gap: 8, flexWrap: \"wrap\", marginBottom: 12 }}>',
  "        {FILTER_OPTIONS.map(([key, label]) => (",
  "          <button",
  "            key={key}",
  "            type=\"button\"",
  "            onClick={() => setFilter(key)}",
  "            style={{",
  "              padding: \"6px 12px\",",
  "              borderRadius: 8,",
  "              border: \"1px solid #444\",",
  "              background: filter === key ? \"#222\" : \"transparent\",",
  "              color: \"inherit\",",
  "              cursor: \"pointer\",",
  "            }}",
  "          >",
  "            {label}",
  "          </button>",
  "        ))}",
  "      </div>",
  "      {loading && <div>Loading orders…</div>}",
  "      {!loading && error && (",
  "        <div style={{ color: \"crimson\" }}>",
  "          {error} ",
  "          <button type=\"button\" onClick={() => window.location.reload()}>Retry</button>",
  "        </div>",
  "      )}",
  "      {!loading && !error && filteredOrders.length === 0 && (",
  "        <div>No orders for this filter.</div>",
  "      )}",
  "      {!loading && !error && filteredOrders.length > 0 && (",
  "        <div style={{ border: \"1px solid #333\", borderRadius: 12, overflow: \"hidden\" }}>",
  '          <div style={{ display: "grid", gridTemplateColumns: "150px 140px 120px 220px 1fr", gap: 8, padding: 10, fontWeight: 700, borderBottom: "1px solid #333" }}>',
  "            <div>Order</div>",
  "            <div>Status</div>",
  "            <div>Total</div>",
  "            <div>Created</div>",
  "            <div>Actions</div>",
  "          </div>",
  "          {filteredOrders.map((order) => {",
  "            const status = normalizeStatus(order.status || order.paymentStatus);",
  "            const shortId = (order.id || '').slice(0, 8) || '—';",
  "            const created = order.createdAt",
  "              ? new Date(order.createdAt).toLocaleString()",
  "              : '—';",
  "            return (",
  "              <div",
  "                key={order.id}",
  "                style={{",
  "                  display: \"grid\",",
  "                  gridTemplateColumns: \"150px 140px 120px 220px 1fr\",",
  "                  gap: 8,",
  "                  padding: 10,",
  "                  borderBottom: \"1px solid #2a2a2a\",",
  "                }}",
  "              >",
  "                <div>{shortId}</div>",
  "                <div>{status || '—'}</div>",
  "                <div>{formatMoney(order)}</div>",
  "                <div>{created}</div>",
  "                <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>",
  "                  <button",
  "                    type=\"button\"",
  "                    style={{",
  "                      padding: '6px 10px',",
  "                      borderRadius: 8,",
  "                      border: '1px solid #444',",
  "                      background: 'transparent',",
  "                      cursor: 'pointer',",
  "                    }}",
  "                    onClick={() => navigate(`/buyer/orders/${order.id}`)}",
  "                  >",
  "                    View",
  "                  </button>",
  "                  {isUnpaidStatus(status) && (",
  "                    <button",
  "                      type=\"button\"",
  "                      style={{",
  "                        padding: '6px 10px',",
  "                        borderRadius: 8,",
  "                        border: '1px solid #444',",
  "                        background: '#222',",
  "                        color: 'white',",
  "                        cursor: 'pointer',",
  "                      }}",
  "                      onClick={() => navigate(`/buyer/orders/${order.id}`)}",
  "                    >",
  "                      Pay now",
  "                    </button>",
  "                  )}",
  "                </div>",
  "              </div>",
  "            );",
  "          })}",
  "        </div>",
  "      )}",
  "    </div>",
  "  );",
  "}",
];

const tsxContent = tsxLines.join("\n");
const base64Content = Buffer.from(tsxContent, "utf8").toString("base64");
fs.writeFileSync(base64Path, base64Content, "utf8");
const decoded = Buffer.from(base64Content, "base64").toString("utf8");
fs.writeFileSync(targetPath, decoded, "utf8");
console.log(
  `restored ${targetPath} (${Buffer.byteLength(decoded, "utf8")} bytes) from base64 ${base64Path}`
);
